plugins {
    id 'java-library'
    id 'io.qameta.allure' version '2.11.2'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

def allureVersion = "2.21.0",
selenideVersion = "6.19.1"

allure {
    report {
        version.set(allureVersion)
    }
    adapter {
        aspectjWeaver.set(true)
        frameworks {
            junit5 {
                adapterVersion.set(allureVersion)
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation (
            "com.codeborne:selenide:$selenideVersion",
            "io.qameta.allure:allure-selenide:$allureVersion",
            'com.github.javafaker:javafaker:1.0.2',
            'org.junit.jupiter:junit-jupiter:5.10.0',
            'org.slf4j:slf4j-simple:2.0.17')

    testRuntimeOnly(
        "org.slf4j:slf4j-simple:2.0.17")
}

task web_test(type: Test) {
    useJUnitPlatform {
        includeTags("web")
    }
}
